# This file contains the configuration for the game
rank_weights:
  E: 15
  D: 35
  C: 30
  B: 15
  A: 5
  S: 1

# Class Mechanic
allow_class_change: false
class_change_cooldown: 30 # Cooldown in seconds for class change

# Reborn Mechanic
reset_class_on_death: true
reborn_cooldown: 30 # Cooldown in seconds for reborn