name: EndlessLegends
version: '${project.version}'
main: com.airijko.endlesslegends.EndlessLegends
depend: [EndlessCore]
api-version: '1.20'
commands:
  endlesslegends:
    description: Main command for EndlessLegends.
    usage: /<command> [reload|getattributesummary|profile|class|cc|chooseclass]
  class:
    description: Choose your class
    usage: /<command>
    aliases: [cc]
  chooseclass:
    description: Choose your class
    usage: /<command> <class>
    aliases: [cc]
  testchooseclass:
    description: Choose your class
    usage: /<command> <class>
    aliases: [cc]

